const sentences = {
  0: "The sun sets behind the mountains.",
  1: "A quick brown fox jumps over the lazy dog in the park on a sunny day.",
  2: "The rain fell in a steady, soothing rhythm.",
  3: "Her eyes sparkled with joy and excitement as she opened the gift.",
  4: "He couldn't believe it was already Friday.",
  5: "They danced under the stars until dawn.",
  6: "A cup of coffee is the best way to start the morning.",
  7: "The cat sat on the windowsill, watching the birds.",
  8: "The streets were empty in the early hours of the morning.",
  9: "She picked up the phone and dialed the familiar number.",
  10: "The sound of laughter filled the room.",
  11: "A warm breeze blew through the open window.",
  12: "The car sped down the highway as the sun rose in the distance.",
  13: "He stared at the blank page, waiting for inspiration to strike.",
  14: "The book had a thick layer of dust on the cover.",
  15: "She whispered a secret in his ear and smiled.",
  16: "The clock ticked loudly in the silent room.",
  17: "A sudden thunderstorm broke the calm afternoon.",
  18: "The ice cream melted in the heat of the summer sun.",
  19: "They watched the fireworks light up the night sky.",
  20: "The garden was in full bloom with vibrant colors.",
  21: "He took a deep breath and jumped into the pool.",
  22: "The train arrived at the station right on time.",
  23: "A bird chirped cheerfully outside the window.",
  24: "She packed her suitcase and headed for the airport.",
  25: "The sun peeked through the clouds after a rainy day.",
  26: "He scribbled notes in the margins of the book.",
  27: "The aroma of freshly baked bread filled the kitchen.",
  28: "A dog barked in the distance as the moon rose.",
  29: "They shared stories around the campfire under the stars.",
  30: "The beach was quiet except for the sound of waves.",
  31: "The children laughed as they chased each other through the park.",
  32: "She opened the window and let in the cool night air.",
  33: "The leaves rustled in the wind, signaling the arrival of fall.",
  34: "He listened to the rain tapping on the roof as he drifted to sleep.",
  35: "The city lights flickered in the distance as the taxi drove away.",
  36: "The silence of the forest was broken by a single bird's call.",
  37: "She hummed a tune as she walked down the empty street.",
  38: "The cup of tea sat untouched on the table.",
  39: "The sunset painted the sky in shades of pink and orange.",
  40: "He flipped through the pages of the old photo album.",
  41: "The sound of the ocean waves was calming and peaceful.",
  42: "She sat by the fire, wrapped in a cozy blanket.",
  43: "The clouds rolled in, bringing with them the promise of rain.",
  44: "He adjusted his tie in the mirror before heading out the door.",
  45: "A single candle flickered in the dark room.",
  46: "The snow fell softly, covering the ground in a white blanket.",
  47: "She watched the stars twinkle in the clear night sky.",
  48: "The sound of footsteps echoed in the empty hallway.",
  49: "The old clock on the wall chimed midnight.",
  50: "A gentle breeze rustled the curtains, bringing in the scent of flowers.",
  51: "The children built a sandcastle on the beach as the tide came in.",
  52: "He sat on the porch, watching the rain fall.",
  53: "She smiled as she watched the sun rise over the horizon.",
  54: "The road stretched out before them, endless and empty.",
  55: "A bird flew past the window, disappearing into the clouds.",
  56: "The coffee shop was quiet, except for the hum of conversation.",
  57: "The flowers in the garden swayed gently in the breeze.",
  58: "He opened the letter and began to read, his heart racing.",
  59: "The air was thick with the scent of pine trees and earth.",
  60: "She turned the page of her book, lost in the story.",
  61: "The rain began to fall harder, tapping on the windows.",
  62: "He looked up at the sky, watching the clouds move slowly.",
  63: "The restaurant was bustling with people enjoying their meals.",
  64: "A cat meowed softly from the alleyway as they passed by.",
  65: "The stars shone brightly in the clear night sky.",
  66: "She closed her eyes and listened to the sound of the waves.",
  67: "The room was filled with the soft glow of candlelight.",
  68: "He picked up his guitar and strummed a few chords.",
  69: "The leaves on the trees turned shades of red, orange, and yellow.",
  70: "The smell of freshly baked cookies filled the house.",
  71: "The sun dipped below the horizon, casting a golden glow.",
  72: "He sat at his desk, staring at the blank computer screen.",
  73: "The wind howled through the trees, shaking the branches.",
  74: "She tied her shoes and set off on her morning run.",
  75: "The old man sat on the park bench, feeding the pigeons.",
  76: "The classroom was silent as the teacher handed out the exams.",
  77: "A gentle rain fell, soaking the ground.",
  78: "The bus arrived late, as usual.",
  79: "She waited at the train station, her suitcase by her side.",
  80: "He watched the sunset from the top of the hill.",
  81: "The bakery was filled with the scent of fresh bread and pastries.",
  82: "The lights of the city sparkled in the distance.",
  83: "She wrapped her scarf tighter against the cold wind.",
  84: "The fire crackled in the hearth, warming the room.",
  85: "The plane took off smoothly, climbing into the clouds.",
  86: "He played a soft melody on the piano, filling the room with music.",
  87: "The boat rocked gently on the waves as they sailed out to sea.",
  88: "The snow crunched under their boots as they walked through the forest.",
  89: "She gazed out the window, watching the raindrops slide down the glass.",
  90: "The market was alive with the sounds of vendors and shoppers.",
  91: "He flipped the pancake in the pan, laughing as it landed perfectly.",
  92: "The mountain loomed in the distance, covered in a blanket of snow.",
  93: "She scribbled a note on the paper, her pen moving quickly.",
  94: "The clock on the wall ticked steadily as the minutes passed.",
  95: "The breeze was warm, carrying the scent of the ocean.",
  96: "He took a deep breath and stepped onto the stage.",
  97: "The library was quiet, except for the soft rustle of pages.",
  98: "The streets were empty, lit only by the glow of the streetlights.",
  99: "She slipped the ring onto her finger, smiling softly.",
  100: "The moon was full, casting a pale light over the landscape.",
  101: "The sun was shining brightly, warming the earth below.",
  102: "He walked through the city streets, lost in thought.",
  103: "The coffee was too hot, but he drank it anyway.",
  104: "The train whistle blew, echoing through the quiet town.",
  105: "She danced in the rain, her laughter filling the air.",
  106: "The old wooden chair creaked as he sat down.",
  107: "The flowers in the vase were wilting, petals falling one by one.",
  108: "A dog barked loudly in the distance, breaking the silence.",
  109: "The waiter brought their food, the plates steaming with heat.",
  110: "She unlocked the door and stepped into the dark apartment.",
  111: "The campfire crackled, sending sparks into the night sky.",
  112: "He glanced at his watch and realized he was running late.",
  113: "The airplane soared above the clouds, leaving the ground far behind.",
  114: "A small bird perched on the windowsill, chirping happily.",
  115: "The beach was crowded with families enjoying the summer day.",
  116: "She tied her hair back and got to work, determined to finish.",
  117: "The phone buzzed on the table, but he ignored it.",
  118: "The car engine roared to life, ready for the long journey ahead.",
  119: "The wind blew her hair in all directions as she stood by the sea.",
  120: "The old record player crackled as the music started.",
  121: "He pulled the blanket tighter around himself as the temperature dropped.",
  122: "The bookstore was filled with the smell of new and old books.",
  123: "The stars twinkled in the sky, millions of miles away.",
  124: "She laughed at his joke, her eyes crinkling with amusement.",
  125: "The rain stopped just as they reached the car.",
  126: "He scrolled through his phone, looking for something to watch.",
  127: "The streetlights flickered as they walked through the quiet neighborhood.",
  128: "She stirred the soup, the smell of herbs filling the kitchen.",
  129: "The sound of children playing echoed through the park.",
  130: "The pages of the book felt smooth under her fingers as she turned them.",
  131: "He ran his hand through his hair, trying to calm his nerves.",
  132: "The clock struck midnight, and the party was just getting started.",
  133: "She smiled as she watched the children chase after the ice cream truck.",
  134: "The doorbell rang, interrupting his thoughts.",
  135: "The waves crashed against the shore, spraying mist into the air.",
  136: "He opened the fridge, searching for something to eat.",
  137: "The garden was overgrown, weeds choking the flowers.",
  138: "The sun dipped below the horizon, leaving a golden glow in the sky.",
  139: "She flipped the light switch, illuminating the cozy room.",
  140: "The crowd cheered as the band took the stage.",
  141: "He shuffled through the papers on his desk, looking for the right document.",
  142: "The snow fell gently, covering the world in a white blanket.",
  143: "She sighed and leaned back in her chair, exhausted from the day.",
  144: "The bus ride was long, but the scenery was beautiful.",
  145: "The fire pit crackled and popped as they roasted marshmallows.",
  146: "He checked his phone again, hoping for a message that never came.",
  147: "The sky was a brilliant blue, without a cloud in sight.",
  148: "She carefully arranged the flowers in the vase, admiring her work.",
  149: "The city skyline was breathtaking as the sun set behind the buildings.",
  150: "He smiled to himself as he remembered the day they met.",
  151: "The sound of birds chirping woke her up early in the morning.",
  152: "The suitcase was packed, and the taxi was waiting outside.",
  153: "He pulled the hood of his jacket up as the rain started to fall.",
  154: "The wind howled outside, rattling the windows.",
  155: "She baked a cake for the party, decorating it with colorful frosting.",
  156: "The lake was calm, reflecting the mountains in the distance.",
  157: "He glanced out the window, watching the storm roll in.",
  158: "The coffee shop was warm and cozy, a perfect escape from the cold.",
  159: "She hummed a tune as she cleaned the house, lost in her thoughts.",
  160: "The moon shone brightly, lighting their way through the dark forest.",
  161: "He scribbled notes in the margins of his notebook during the lecture.",
  162: "The bakery smelled of fresh bread and cinnamon, making her mouth water.",
  163: "The park was quiet, except for the occasional rustle of leaves.",
  164: "She tied her shoelaces and prepared for her morning jog.",
  165: "The train rumbled down the tracks, heading towards the next station.",
  166: "He played his guitar softly, the notes echoing through the empty house.",
  167: "The smell of popcorn filled the movie theater as the lights dimmed.",
  168: "She wrapped her arms around herself, trying to ward off the cold.",
  169: "The old wooden bridge creaked as they crossed it.",
  170: "He watched as the sun rose, painting the sky in shades of pink and orange.",
  171: "The room was filled with laughter as they shared stories from the past.",
  172: "She picked up the phone and dialed the familiar number.",
  173: "The coffee cup sat abandoned on the counter, half-empty and cold.",
  174: "He threw the frisbee, watching it soar through the air.",
  175: "The fire crackled in the fireplace, casting a warm glow on the room.",
  176: "The mountain trail was steep, but the view from the top was worth it.",
  177: "She poured herself a glass of wine and sat down to relax.",
  178: "The ocean waves crashed against the rocks, sending spray into the air.",
  179: "He pulled the blanket over his head, trying to block out the noise.",
  180: "The sound of the piano filled the room, soft and melodic.",
  181: "She stood in front of the mirror, adjusting her dress.",
  182: "The boat rocked gently on the calm waters of the lake.",
  183: "He checked his watch, realizing he was going to be late.",
  184: "The candle flickered in the breeze, casting dancing shadows on the walls.",
  185: "She sat by the window, watching the world go by.",
  186: "The sound of rain on the roof was soothing, lulling him to sleep.",
  187: "The air was thick with humidity, making it hard to breathe.",
  188: "He watched the clouds drift lazily across the sky.",
  189: "She scribbled a note and left it on the kitchen counter.",
  190: "The old man sat on the park bench, feeding the pigeons.",
  191: "The restaurant was bustling with activity as the dinner rush began.",
  192: "He stood on the balcony, looking out at the city below.",
  193: "The stars sparkled in the night sky, distant and unreachable.",
  194: "She slipped her hand into his, and they walked in comfortable silence.",
  195: "The waves lapped at the shore, gently pulling the sand back into the ocean.",
  196: "He stared at the blank page, waiting for the words to come.",
  197: "The flowers in the garden swayed gently in the breeze.",
  198: "She watched the fireflies dance in the darkness.",
  199: "The sun was setting, casting long shadows on the ground.",
  200: "He sighed and closed the book, setting it down on the table.",
};

const d = document;
const $ = (el) => d.querySelector(el);
const $textarea = $("textarea");

d.addEventListener("click", (e) => {
  if (e.target.matches(".btn-gradient")) {
    const numeroRandom = Math.floor(Math.random() * 201);
    $textarea.value = sentences[numeroRandom];
    return;
  }
  if (e.target.matches(".delete")) {
    $textarea.value = "";
    return;
  }

  if (e.target.matches(".copy")) {
    $textarea.select();
    $textarea.setSelectionRange(0, 5000000);
    navigator.clipboard.writeText($textarea.value);
    return;
  }
});
